apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lunanexa-nvidia-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/part-of: lunanexa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-device-plugin
      app.kubernetes.io/part-of: lunanexa
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-device-plugin
        app.kubernetes.io/part-of: lunanexa
    spec:
      nodeSelector:
        lunanexa.io/role: gpu
      tolerations:
        - key: lunanexa.io/role
          operator: Equal
          value: gpu
          effect: NoSchedule
      priorityClassName: system-node-critical
      runtimeClassName: nvidia
      containers:
        - name: nvidia-device-plugin
          image: nvcr.io/nvidia/k8s-device-plugin@sha256:25cc340fe6fd53c101e16fc452f503e7a92c219c64a80ed5381784b522dbbf77
          imagePullPolicy: IfNotPresent
          env:
            - name: FAIL_ON_INIT_ERROR
              value: "true"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: kubelet-device-plugins
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: kubelet-device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
