kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lunanexa-sim
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "lunanexa.io/role=management,lunanexa.io/simulation=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "lunanexa.io/role=gpu,lunanexa.io/simulation=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "lunanexa.io/role=gpu,lunanexa.io/simulation=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "lunanexa.io/role=gpu,lunanexa.io/simulation=true"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "lunanexa.io/role=gpu,lunanexa.io/simulation=true"
